const airports=[
{code:"ATL",name:"Hartsfield-Jackson Atlanta International",city:"Atlanta",state:"GA",region:"Southeast",lat:33.6407,lon:-84.4277,type:"hub",flights:2784,delay:16.8,cancel:1.2,weather:"Clear · Wind 7 kt"},
{code:"ORD",name:"Chicago O'Hare International",city:"Chicago",state:"IL",region:"Midwest",lat:41.9742,lon:-87.9073,type:"hub",flights:2381,delay:27.4,cancel:2.9,weather:"Broken clouds · Wind 14 kt"},
{code:"DFW",name:"Dallas Fort Worth International",city:"Dallas",state:"TX",region:"South Central",lat:32.8998,lon:-97.0403,type:"hub",flights:2517,delay:19.2,cancel:1.5,weather:"Clear · Wind 11 kt"},
{code:"DEN",name:"Denver International",city:"Denver",state:"CO",region:"Mountain",lat:39.8561,lon:-104.6737,type:"hub",flights:2240,delay:21.6,cancel:1.8,weather:"Scattered clouds · Wind 18 kt"},
{code:"LAX",name:"Los Angeles International",city:"Los Angeles",state:"CA",region:"West Coast",lat:33.9416,lon:-118.4085,type:"hub",flights:1962,delay:17.5,cancel:.9,weather:"Haze · Wind 6 kt"},
{code:"SFO",name:"San Francisco International",city:"San Francisco",state:"CA",region:"West Coast",lat:37.6213,lon:-122.379,type:"hub",flights:1429,delay:29.7,cancel:2.4,weather:"Fog · Wind 12 kt"},
{code:"CLT",name:"Charlotte Douglas International",city:"Charlotte",state:"NC",region:"Southeast",lat:35.214,lon:-80.9431,type:"hub",flights:1905,delay:15.2,cancel:1.1,weather:"Clear · Wind 5 kt"},
{code:"JFK",name:"John F. Kennedy International",city:"New York",state:"NY",region:"Northeast",lat:40.6413,lon:-73.7781,type:"hub",flights:1580,delay:31.3,cancel:3.1,weather:"Rain showers · Wind 17 kt"},
{code:"EWR",name:"Newark Liberty International",city:"Newark",state:"NJ",region:"Northeast",lat:40.6895,lon:-74.1745,type:"hub",flights:1364,delay:33.1,cancel:3.4,weather:"Rain showers · Wind 16 kt"},
{code:"SEA",name:"Seattle-Tacoma International",city:"Seattle",state:"WA",region:"Northwest",lat:47.4502,lon:-122.3088,type:"hub",flights:1318,delay:18.4,cancel:1.3,weather:"Light rain · Wind 8 kt"},
{code:"MIA",name:"Miami International",city:"Miami",state:"FL",region:"Southeast",lat:25.7959,lon:-80.287,type:"hub",flights:1189,delay:22.8,cancel:1.6,weather:"Thunderstorms · Wind 10 kt"},
{code:"BOS",name:"Boston Logan International",city:"Boston",state:"MA",region:"Northeast",lat:42.3656,lon:-71.0096,type:"hub",flights:1267,delay:24.5,cancel:2.2,weather:"Overcast · Wind 15 kt"},
{code:"MSP",name:"Minneapolis-Saint Paul International",city:"Minneapolis",state:"MN",region:"Midwest",lat:44.8848,lon:-93.2223,type:"hub",flights:1128,delay:14.1,cancel:1.2,weather:"Clear · Wind 9 kt"},
{code:"PHX",name:"Phoenix Sky Harbor International",city:"Phoenix",state:"AZ",region:"Southwest",lat:33.4342,lon:-112.0116,type:"hub",flights:1452,delay:12.9,cancel:.7,weather:"Clear · Wind 4 kt"},
{code:"BTV",name:"Patrick Leahy Burlington International",city:"Burlington",state:"VT",region:"Northeast",lat:44.4719,lon:-73.1533,type:"regional",flights:46,delay:18.9,cancel:2.1,weather:"Cloudy · Wind 11 kt"},
{code:"AVL",name:"Asheville Regional",city:"Asheville",state:"NC",region:"Southeast",lat:35.4362,lon:-82.5418,type:"regional",flights:58,delay:12.7,cancel:1.1,weather:"Clear · Wind 4 kt"},
{code:"ROA",name:"Roanoke-Blacksburg Regional",city:"Roanoke",state:"VA",region:"Southeast",lat:37.3255,lon:-79.9754,type:"regional",flights:34,delay:11.6,cancel:1.4,weather:"Clear · Wind 3 kt"},
{code:"CHO",name:"Charlottesville-Albemarle",city:"Charlottesville",state:"VA",region:"Southeast",lat:38.1386,lon:-78.4529,type:"regional",flights:28,delay:9.8,cancel:.8,weather:"Partly cloudy · Wind 4 kt"},
{code:"FAT",name:"Fresno Yosemite International",city:"Fresno",state:"CA",region:"West Coast",lat:36.7762,lon:-119.7181,type:"regional",flights:55,delay:13.4,cancel:.9,weather:"Haze · Wind 3 kt"},
{code:"BOI",name:"Boise Airport",city:"Boise",state:"ID",region:"Mountain",lat:43.5644,lon:-116.2228,type:"regional",flights:69,delay:10.7,cancel:.6,weather:"Clear · Wind 6 kt"},
{code:"TUS",name:"Tucson International",city:"Tucson",state:"AZ",region:"Southwest",lat:32.1161,lon:-110.941,type:"regional",flights:47,delay:8.9,cancel:.5,weather:"Clear · Wind 5 kt"},
{code:"PWM",name:"Portland International Jetport",city:"Portland",state:"ME",region:"Northeast",lat:43.6462,lon:-70.3093,type:"regional",flights:48,delay:16.2,cancel:1.9,weather:"Overcast · Wind 10 kt"},
{code:"GSP",name:"Greenville-Spartanburg International",city:"Greenville",state:"SC",region:"Southeast",lat:34.8957,lon:-82.2189,type:"regional",flights:63,delay:10.3,cancel:.7,weather:"Clear · Wind 5 kt"},
{code:"ABQ",name:"Albuquerque International Sunport",city:"Albuquerque",state:"NM",region:"Southwest",lat:35.0402,lon:-106.609,type:"regional",flights:73,delay:11.8,cancel:.8,weather:"Clear · Wind 9 kt"},
{code:"LGA",name:"LaGuardia Airport",city:"New York",state:"NY",region:"Northeast",lat:40.7769,lon:-73.874,type:"hub",flights:1210,delay:28.6,cancel:3,weather:"Rain showers · Wind 15 kt"},
{code:"LAS",name:"Harry Reid International",city:"Las Vegas",state:"NV",region:"Southwest",lat:36.084,lon:-115.1537,type:"hub",flights:1380,delay:16.4,cancel:1,weather:"Clear · Wind 8 kt"},
{code:"DTW",name:"Detroit Metropolitan Wayne County",city:"Detroit",state:"MI",region:"Midwest",lat:42.2162,lon:-83.3554,type:"hub",flights:994,delay:15.8,cancel:1.4,weather:"Cloudy · Wind 10 kt"},
{code:"IAD",name:"Washington Dulles International",city:"Washington",state:"VA",region:"Mid-Atlantic",lat:38.9531,lon:-77.4565,type:"hub",flights:877,delay:20.1,cancel:1.5,weather:"Partly cloudy · Wind 7 kt"},
{code:"DCA",name:"Ronald Reagan Washington National",city:"Washington",state:"DC",region:"Mid-Atlantic",lat:38.8512,lon:-77.0402,type:"hub",flights:931,delay:18.7,cancel:1.8,weather:"Partly cloudy · Wind 6 kt"},
{code:"BWI",name:"Baltimore/Washington International",city:"Baltimore",state:"MD",region:"Mid-Atlantic",lat:39.1774,lon:-76.6684,type:"hub",flights:1085,delay:17.2,cancel:1.3,weather:"Partly cloudy · Wind 6 kt"},
{code:"LYH",name:"Lynchburg Regional",city:"Lynchburg",state:"VA",region:"Southeast",lat:37.3267,lon:-79.2004,type:"regional",flights:18,delay:14.8,cancel:2.2,weather:"Clear · Wind 3 kt"}];
const months=["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"],networkTrend=[18,19,16,17,18,22,25,24,19,17,18,23];
const causeBase={carrier:5.6,weather:3.8,nas:6.7,security:.3,late:7.4};
let selected=airports.find(a=>a.code==="ORD"),markerLayer,heatLayer,routeLayer,selectedRoute,routeLinesByRoute=new Map();
const routes=[["ATL","JFK",1480],["ATL","DFW",1740],["ATL","CLT",1240],["ATL","MIA",1320],["ATL","ORD",1590],["ATL","BOS",970],["ORD","JFK",1340],["ORD","DEN",1650],["ORD","SFO",1010],["ORD","SEA",940],["ORD","BOS",1080],["ORD","MSP",970],["ORD","DFW",1510],["ORD","LAX",1420],["ORD","ATL",1590],["ORD","EWR",1160],["ORD","MIA",870],["ORD","CLT",1040],["ORD","PHX",980],["ORD","BTV",230],["DFW","DEN",1390],["DFW","LAX",1550],["DFW","PHX",1120],["DEN","SFO",970],["DEN","SEA",1050],["DEN","PHX",1180],["LAX","SFO",1380],["LAX","SEA",1060],["JFK","BOS",1160],["JFK","MIA",1230],["JFK","BTV",280],["CLT","ROA",270],["CLT","AVL",340],["SFO","FAT",260],["SEA","BOI",310],["PHX","TUS",280]];
const routeSummary=[
{origin:"ATL",destination:"JFK",route:"ATL-JFK",flights:1480,delay:25.6,cancel:2.1,variability:32.5,severity:"high"},
{origin:"LAX",destination:"SFO",route:"LAX-SFO",flights:1380,delay:28.3,cancel:2,variability:35.9,severity:"high"},
{origin:"ORD",destination:"LGA",route:"ORD-LGA",flights:1260,delay:34.8,cancel:3.8,variability:43.1,severity:"severe"},
{origin:"DFW",destination:"DEN",route:"DFW-DEN",flights:1390,delay:20.4,cancel:1.4,variability:27.3,severity:"moderate"},
{origin:"SFO",destination:"EWR",route:"SFO-EWR",flights:730,delay:38.6,cancel:3.5,variability:47.2,severity:"severe"},
{origin:"CLT",destination:"ATL",route:"CLT-ATL",flights:1240,delay:16.1,cancel:1,variability:22.8,severity:"moderate"},
{origin:"JFK",destination:"LAX",route:"JFK-LAX",flights:920,delay:30.7,cancel:2.7,variability:39.1,severity:"severe"},
{origin:"DEN",destination:"SEA",route:"DEN-SEA",flights:1050,delay:23.9,cancel:1.6,variability:30.5,severity:"high"},
{origin:"ORD",destination:"JFK",route:"ORD-JFK",flights:1340,delay:32.4,cancel:3.2,variability:40.7,severity:"severe"},
{origin:"DEN",destination:"SFO",route:"DEN-SFO",flights:970,delay:26.7,cancel:2.1,variability:34.9,severity:"high"}];
const airlines=[["Delta","DL",14.2,1,82.4,14,21,36],["American","AA",18.5,1.7,77.8,15,25,33],["United","UA",19.1,1.8,77.1,17,22,30],["Southwest","WN",17.8,1.4,78.5,13,24,42],["JetBlue","B6",25.7,2.9,70.3,18,25,27],["Alaska","AS",13.6,.9,83,16,22,36],["Spirit","NK",23.9,2.4,71.6,12,31,34],["Frontier","F9",22.4,2.1,73.2,13,29,33]];
const seasons=[["Winter",23.6,2.8,27,24],["Spring",15.4,1.1,13,27],["Summer",22.1,1.7,21,32],["Fall",14.8,.9,11,25]];
const byCode=code=>airports.find(a=>a.code===code),fmt=n=>n.toLocaleString("en-US"),svgNS="http://www.w3.org/2000/svg";
function clock(){document.querySelector("#utc-clock").textContent=new Date().toISOString().slice(11,19)}clock();setInterval(clock,1000);
const map=L.map("map",{zoomControl:false,scrollWheelZoom:true}).setView([38.2,-97],4);L.control.zoom({position:"bottomright"}).addTo(map);
L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:'&copy; <a href="https://carto.com/">CARTO</a>'}).addTo(map);
function metricValue(a){const key=document.querySelector("#map-metric").value,factor=globalFactor();return key==="cancel"?a.cancel*Math.sqrt(factor):key==="flights"?a.flights:a.delay*factor}
function markerRadius(a){const key=document.querySelector("#map-metric").value,value=metricValue(a);return key==="flights"?5+Math.sqrt(value)/7:key==="cancel"?5+value*3:5+value/2.2}
function markerColor(a){const key=document.querySelector("#map-metric").value,v=metricValue(a);const high=key==="flights"?1800:key==="cancel"?2.2:24,med=key==="flights"?900:key==="cancel"?1.2:17;return v>high?"#fa6b74":v>med?"#ffc857":"#43c6e7"}
function visibleAirports(){const type=document.querySelector("#airport-type").value,threshold=+document.querySelector("#delay-threshold").value;return airports.filter(a=>(type==="all"||a.type===type)&&a.delay>=threshold)}
function severityColor(severity){return severity==="severe"?"#fa6b74":severity==="high"?"#ff8a55":severity==="moderate"?"#ffc857":"#5bd39a"}
function routeTooltip(r){return `<b>${r.route}</b><br>${fmt(r.flights)} flights<br>${r.delay.toFixed(1)}m avg delay · ${r.cancel.toFixed(1)}% cancelled<br>${r.variability.toFixed(1)}m variability · ${r.severity.toUpperCase()}`}
function highlightRoute(r){selectedRoute=r;document.querySelectorAll(".route-row").forEach(row=>row.classList.toggle("active",row.dataset.route===r.route));routeLinesByRoute.forEach((line,route)=>{const data=routeSummary.find(item=>item.route===route);line.setStyle({color:severityColor(data.severity),weight:1.2+data.flights/520,opacity:.48});if(line._path)line._path.classList.remove("route-line-selected")});const activeLine=routeLinesByRoute.get(r.route);if(activeLine){activeLine.setStyle({color:"#ffffff",weight:3.4+r.flights/450,opacity:1});activeLine.bringToFront();if(activeLine._path)activeLine._path.classList.add("route-line-selected")}document.querySelector("#route-detail").innerHTML=`<p class="kicker cyan">SELECTED ROUTE</p><strong>${r.origin} → ${r.destination}</strong><span>${r.delay.toFixed(1)} MIN AVERAGE DELAY</span><small>${fmt(r.flights)} flights · ${r.cancel.toFixed(1)}% cancelled · ${r.variability.toFixed(1)}m variability · ${r.severity.toUpperCase()} severity</small>`}
function renderMap(){if(markerLayer)map.removeLayer(markerLayer);if(heatLayer)map.removeLayer(heatLayer);if(routeLayer)map.removeLayer(routeLayer);routeLinesByRoute=new Map();const list=visibleAirports(),codes=new Set(list.map(a=>a.code)),layer=document.querySelector("#map-layer").value,routeMode=document.querySelector("#route-lines").value;markerLayer=L.layerGroup(list.map(a=>{const m=L.circleMarker([a.lat,a.lon],{radius:markerRadius(a),color:"#d7edf3",weight:1,fillColor:markerColor(a),fillOpacity:.82});m.bindTooltip(`<b>${a.code}</b> · ${a.name}<br>${a.city}, ${a.state}<br>${fmt(a.flights)} flights · ${a.delay.toFixed(1)}m avg delay<br>${a.cancel.toFixed(1)}% cancelled · ${(a.delay*1.28).toFixed(1)}m variability`,{direction:"top"});m.on("click",()=>selectAirport(a,true));return m}));heatLayer=L.heatLayer(list.map(a=>[a.lat,a.lon,Math.max(.2,a.delay/34)]),{radius:31,blur:23,maxZoom:6,gradient:{.2:"#43c6e7",.55:"#ffc857",1:"#fa6b74"}});const mapRoutes=routeSummary.filter(r=>codes.has(r.origin)&&codes.has(r.destination)&&(routeMode==="all"||r.delay>=25));routeLayer=L.layerGroup(mapRoutes.map(r=>{const a=byCode(r.origin),b=byCode(r.destination),line=L.polyline([[a.lat,a.lon],[b.lat,b.lon]],{className:"route-line",color:severityColor(r.severity),weight:1.2+r.flights/520,opacity:.64});routeLinesByRoute.set(r.route,line);line.bindTooltip(routeTooltip(r),{sticky:true});line.on("mouseover",()=>highlightRoute(r));line.on("click",()=>highlightRoute(r));return line}));if(routeMode!=="none")routeLayer.addTo(map);if(layer!=="heat")markerLayer.addTo(map);if(layer!=="markers")heatLayer.addTo(map);if(selectedRoute)highlightRoute(selectedRoute);updateGlobalStats(list)}
function trendFor(a){const factor=globalFactor(),bump=(a.delay-18.7)*.62;return networkTrend.map((v,i)=>+((v+bump+Math.sin(i*1.8+a.code.charCodeAt(0))*2.3)*factor).toFixed(1))}
function renderTrend(){if(!window.Plotly)return;const layout={margin:{l:42,r:15,t:18,b:32},paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{family:"IBM Plex Mono",size:10,color:"#7897a7"},xaxis:{gridcolor:"rgba(139,187,208,.08)"},yaxis:{title:"MINUTES",gridcolor:"rgba(139,187,208,.08)"},legend:{orientation:"h",x:.5,xanchor:"center",y:1.14},hovermode:"x unified"};Plotly.newPlot("trend-chart",[{x:months,y:trendFor(selected),name:selected.code,line:{color:"#43c6e7",width:3},mode:"lines+markers"},{x:months,y:networkTrend,name:"NETWORK AVG",line:{color:"#ff8a55",width:2,dash:"dot"},mode:"lines"}],layout,{displayModeBar:false,responsive:true})}
function renderCauses(){if(!window.Plotly)return;const ratio=selected.delay/18.7,labels=["Late aircraft","NAS","Carrier","Weather","Security"],values=[causeBase.late,causeBase.nas,causeBase.carrier,causeBase.weather,causeBase.security].map((v,i)=>+(v*ratio*(i===3&&["ORD","JFK","EWR","MIA"].includes(selected.code)?1.45:1)).toFixed(1));Plotly.newPlot("cause-chart",[{type:"bar",orientation:"h",y:labels,x:values,marker:{color:["#43c6e7","#25a9c2","#ffc857","#ff8a55","#5f8292"]},hovertemplate:"%{y}: %{x} min<extra></extra>"}],{margin:{l:100,r:20,t:18,b:32},paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{family:"IBM Plex Mono",size:10,color:"#8ba7b5"},xaxis:{title:"MINUTES / DELAYED FLIGHT",gridcolor:"rgba(139,187,208,.08)"},yaxis:{gridcolor:"transparent"}},{displayModeBar:false,responsive:true})}
function renderComparison(){const root=d3.select("#comparison-chart");root.selectAll("*").remove();const box=root.node().getBoundingClientRect(),w=box.width||500,h=box.height||290,m={t:20,r:16,b:38,l:42},groups=[{label:"Major hubs",value:d3.mean(airports.filter(a=>a.type==="hub"),a=>a.delay),color:"#43c6e7"},{label:"Regional",value:d3.mean(airports.filter(a=>a.type==="regional"),a=>a.delay),color:"#ff8a55"}],svg=root.append("svg").attr("viewBox",`0 0 ${w} ${h}`),x=d3.scaleBand().domain(groups.map(d=>d.label)).range([m.l,w-m.r]).padding(.42),y=d3.scaleLinear().domain([0,30]).range([h-m.b,m.t]);svg.append("g").attr("transform",`translate(${m.l},0)`).call(d3.axisLeft(y).ticks(5)).call(g=>g.selectAll("text").attr("fill","#7897a7").attr("font-family","IBM Plex Mono").attr("font-size",10)).call(g=>g.selectAll("line").attr("stroke","rgba(139,187,208,.12)")).call(g=>g.select(".domain").remove());svg.selectAll(".bar").data(groups).join("rect").attr("x",d=>x(d.label)).attr("y",d=>y(d.value)).attr("width",x.bandwidth()).attr("height",d=>y(0)-y(d.value)).attr("fill",d=>d.color).attr("opacity",.88);svg.selectAll(".val").data(groups).join("text").attr("x",d=>x(d.label)+x.bandwidth()/2).attr("y",d=>y(d.value)-9).attr("text-anchor","middle").attr("fill","#e6f3f7").attr("font-family","IBM Plex Mono").attr("font-size",12).text(d=>`${d.value.toFixed(1)}m`);svg.append("g").attr("transform",`translate(0,${h-m.b})`).call(d3.axisBottom(x)).call(g=>g.selectAll("text").attr("fill","#9ab3be").attr("font-family","IBM Plex Mono").attr("font-size",10)).call(g=>g.select(".domain").attr("stroke","rgba(139,187,208,.15)"))}
function renderRanking(){document.querySelector("#airport-ranking").innerHTML=[...airports].sort((a,b)=>b.delay-a.delay).slice(0,6).map((a,i)=>`<div class="ranking-item" data-airport="${a.code}"><span>0${i+1}</span><b>${a.code} <small>${a.city.toUpperCase()}</small></b><em>${a.delay.toFixed(1)}m</em></div>`).join("");document.querySelectorAll(".ranking-item").forEach(el=>el.onclick=()=>selectAirport(byCode(el.dataset.airport),true))}
function selectAirport(a,fly=false){selected=a;document.querySelector("#detail-code").textContent=a.code;document.querySelector("#detail-name").textContent=a.name;document.querySelector("#detail-type").textContent=a.type==="hub"?"MAJOR HUB":"REGIONAL";document.querySelector("#detail-delay").textContent=a.delay.toFixed(1);document.querySelector("#detail-location").textContent=`${a.city}, ${a.state} · ${a.region} Region`;document.querySelector("#detail-weather").textContent=`◌ ${a.weather}`;document.querySelector("#detail-flights").textContent=fmt(a.flights);document.querySelector("#detail-cancel").textContent=`${a.cancel.toFixed(1)}%`;document.querySelector("#detail-ontime").textContent=`${Math.max(55,91-a.delay*.73).toFixed(1)}%`;document.querySelector("#detail-rank").textContent=`#${String([...airports].sort((x,y)=>y.delay-x.delay).findIndex(x=>x.code===a.code)+1).padStart(2,"0")}`;document.querySelector("#network-airport").value=a.code;document.querySelector("#map-message").textContent=`${a.code} SELECTED · ${a.delay.toFixed(1)} MIN AVG DELAY`;if(fly)map.flyTo([a.lat,a.lon],a.type==="hub"?5:6,{duration:.7});renderTrend();renderCauses();renderNetwork()}
function connectedRoutes(code){return routes.filter(r=>r[0]===code||r[1]===code).sort((a,b)=>b[2]-a[2]).slice(0,+document.querySelector("#route-limit").value)}
function renderNetwork(){const root=d3.select("#network-chart");root.selectAll("*").remove();const box=root.node().getBoundingClientRect(),w=box.width||900,h=385,list=connectedRoutes(selected.code),codes=[...new Set(list.flatMap(r=>[r[0],r[1]]))],nodes=codes.map(code=>({...byCode(code)})),links=list.map(([source,target,volume])=>({source,target,volume,delay:+((byCode(source).delay+byCode(target).delay)/2).toFixed(1)})),svg=root.append("svg").attr("viewBox",`0 0 ${w} ${h}`),tip=d3.select("body").selectAll(".network-tooltip").data([0]).join("div").attr("class","network-tooltip"),sim=d3.forceSimulation(nodes).force("link",d3.forceLink(links).id(d=>d.code).distance(d=>95+Math.min(50,1700/d.volume))).force("charge",d3.forceManyBody().strength(-360)).force("center",d3.forceCenter(w/2,h/2)).force("collide",d3.forceCollide().radius(d=>d.code===selected.code?34:22));const line=svg.append("g").selectAll("line").data(links).join("line").attr("stroke",d=>d.delay>24?"#ff8a55":"#35a8bf").attr("stroke-opacity",.58).attr("stroke-width",d=>1+d.volume/650).on("mousemove",(e,d)=>tip.style("opacity",1).style("left",`${e.clientX+12}px`).style("top",`${e.clientY+12}px`).html(`${d.source.code} → ${d.target.code}<br>${fmt(d.volume)} flights · ${d.delay}m delay`)).on("mouseleave",()=>tip.style("opacity",0));const node=svg.append("g").selectAll("g").data(nodes).join("g").attr("cursor","pointer").on("click",(e,d)=>selectAirport(d));node.append("circle").attr("r",d=>d.code===selected.code?21:d.type==="hub"?13:9).attr("fill",d=>d.code===selected.code?"#ff8a55":d.type==="hub"?"#43c6e7":"#ffc857").attr("stroke","#d8edf3").attr("stroke-width",1.2);node.append("text").attr("y",d=>d.code===selected.code?36:28).attr("text-anchor","middle").attr("fill","#d8edf3").attr("font-family","IBM Plex Mono").attr("font-size",10).text(d=>d.code);sim.on("tick",()=>{line.attr("x1",d=>d.source.x).attr("y1",d=>d.source.y).attr("x2",d=>d.target.x).attr("y2",d=>d.target.y);node.attr("transform",d=>`translate(${Math.max(30,Math.min(w-30,d.x))},${Math.max(27,Math.min(h-30,d.y))})`)});document.querySelector("#network-code").textContent=selected.code;document.querySelector("#network-routes").textContent=list.length;document.querySelector("#network-volume").textContent=fmt(d3.sum(list,r=>r[2]));document.querySelector("#network-delay").textContent=`${d3.mean(links,r=>r.delay)?.toFixed(1)||"0.0"}m`}
const plotLayout={paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{family:"IBM Plex Mono",size:10,color:"#8ba7b5"},xaxis:{gridcolor:"rgba(139,187,208,.08)"},yaxis:{gridcolor:"rgba(139,187,208,.08)"},legend:{orientation:"h",x:.5,xanchor:"center",y:1.15},margin:{l:46,r:15,t:22,b:42}};
function globalFactor(){const year=+document.querySelector("#year-filter").value,season=document.querySelector("#season-filter").value,airline=document.querySelector("#airline-filter").value,seasonFactor={Winter:1.18,Spring:.88,Summer:1.12,Fall:.84,all:1}[season],airlineRow=airlines.find(a=>a[0]===airline);return ((year-2019)*.022+.89)*seasonFactor*(airlineRow?airlineRow[2]/18.7:1)}
function updateGlobalStats(list=visibleAirports()){const factor=globalFactor(),avg=list.length?d3.mean(list,a=>a.delay)*factor:0,cancel=list.length?d3.mean(list,a=>a.cancel)*Math.sqrt(factor):0;document.querySelector("#stat-delay").innerHTML=`${avg.toFixed(1)}<em>m</em>`;document.querySelector("#stat-cancel").innerHTML=`${cancel.toFixed(1)}<em>%</em>`}
function renderHubAnalysis(){if(!window.Plotly)return;const hubs=["ATL","ORD","DFW","DEN","LAX","SFO","CLT","JFK"].map(byCode),regionals=["ROA","LYH","CHO","BTV","AVL","FAT"].map(byCode),list=[...hubs,...regionals],colors=list.map(a=>a.type==="hub"?"#43c6e7":"#ff8a55"),common={...plotLayout,margin:{l:42,r:12,t:28,b:38},showlegend:false};Plotly.newPlot("hub-delay-chart",[{type:"bar",x:list.map(a=>a.code),y:list.map(a=>a.delay),text:list.map(a=>`${a.delay.toFixed(1)}m`),textposition:"outside",cliponaxis:false,marker:{color:colors},hovertemplate:"%{x}: %{y:.1f} min<extra></extra>"}],common,{displayModeBar:false,responsive:true});Plotly.newPlot("hub-cancel-chart",[{type:"bar",x:list.map(a=>a.code),y:list.map(a=>a.cancel),text:list.map(a=>`${a.cancel.toFixed(1)}%`),textposition:"outside",cliponaxis:false,marker:{color:colors},hovertemplate:"%{x}: %{y:.1f}%<extra></extra>"}],common,{displayModeBar:false,responsive:true});Plotly.newPlot("hub-variability-chart",[{type:"box",name:"Major hubs",y:hubs.map(a=>a.delay*1.28),text:hubs.map(a=>`${a.code}: ${(a.delay*1.28).toFixed(1)}m variability`),hovertemplate:"%{text}<extra></extra>",marker:{color:"#43c6e7"},boxpoints:"all"},{type:"box",name:"Regional",y:regionals.map(a=>a.delay*1.45),text:regionals.map(a=>`${a.code}: ${(a.delay*1.45).toFixed(1)}m variability`),hovertemplate:"%{text}<extra></extra>",marker:{color:"#ff8a55"},boxpoints:"all"}],{...common,showlegend:true},{displayModeBar:false,responsive:true});const hubDelay=d3.mean(hubs,a=>a.delay),regDelay=d3.mean(regionals,a=>a.delay),hubCancel=d3.mean(hubs,a=>a.cancel),regCancel=d3.mean(regionals,a=>a.cancel);document.querySelector("#hub-summary").innerHTML=`<article><small>HUB AVG DELAY</small><strong>${hubDelay.toFixed(1)}<em>m</em></strong><p>High traffic increases network exposure.</p></article><article><small>REGIONAL AVG DELAY</small><strong>${regDelay.toFixed(1)}<em>m</em></strong><p>Lower volume, smaller delay baseline.</p></article><article><small>HUB CANCELLATION RATE</small><strong>${hubCancel.toFixed(1)}<em>%</em></strong><p>Large hubs absorb more congestion.</p></article><article><small>REGIONAL CANCELLATION RATE</small><strong>${regCancel.toFixed(1)}<em>%</em></strong><p>Limited schedules can amplify disruption.</p></article>`}
function renderCauseAnalysis(){if(!window.Plotly)return;const group=document.querySelector("#cause-group").value,labels=group==="season"?seasons.map(s=>s[0]):group==="airport"?["ATL","ORD","DFW","DEN","LAX","SFO","JFK","EWR"]:airlines.map(a=>a[1]),base=[["Weather","#ff8a55",16,"Severe weather or weather-related conditions"],["Carrier","#ffc857",23.5,"Airline operations, maintenance, crew, or aircraft issues"],["NAS","#43c6e7",27.9,"National Airspace System congestion and air traffic control"],["Security","#8099a4",1.1,"Security-related events"],["Late aircraft","#5bd39a",31.5,"Aircraft arriving late from a previous flight"]],traces=base.map(([name,color,value,description],index)=>({type:"bar",name,x:labels,y:labels.map((_,i)=>+(value*(.78+((i*3+index*2)%7)/20)).toFixed(1)),customdata:labels.map(()=>description),marker:{color},hovertemplate:`<b>${name} Delay</b>: %{y:.1f}%<br>%{customdata}<extra></extra>`}));Plotly.newPlot("cause-stacked-chart",traces,{...plotLayout,barmode:"stack",yaxis:{title:"SHARE OF DELAY MINUTES",gridcolor:"rgba(139,187,208,.08)"}},{displayModeBar:false,responsive:true});Plotly.newPlot("cause-donut-chart",[{type:"pie",hole:.62,labels:base.map(b=>b[0]),values:base.map(b=>b[2]),customdata:base.map(b=>b[3]),marker:{colors:base.map(b=>b[1])},textinfo:"label+percent",hovertemplate:"<b>%{label} Delay</b>: %{value:.1f}%<br>%{customdata}<extra></extra>"}],{...plotLayout,margin:{l:10,r:10,t:10,b:10},showlegend:false},{displayModeBar:false,responsive:true})}
function renderAirlines(){if(!window.Plotly)return;document.querySelector("#airline-cards").innerHTML=airlines.map(a=>`<article class="airline-card" data-airline="${a[0]}"><small>${a[1]} / ON-TIME</small><strong>${a[0]}</strong><b>${a[4].toFixed(1)}%</b><p>${a[2].toFixed(1)}m avg delay · ${a[3].toFixed(1)}% cancelled</p></article>`).join("");document.querySelectorAll(".airline-card").forEach(card=>card.onclick=()=>{document.querySelector("#airline-filter").value=card.dataset.airline;refreshDashboard()});const sorted=[...airlines].sort((a,b)=>b[2]-a[2]);Plotly.newPlot("airline-ranking-chart",[{type:"bar",orientation:"h",y:sorted.map(a=>a[0]),x:sorted.map(a=>a[2]),marker:{color:sorted.map(a=>a[2]>22?"#fa6b74":a[2]>17?"#ffc857":"#43c6e7")},hovertemplate:"%{y}: %{x:.1f} min<extra></extra>"}],{...plotLayout,margin:{l:78,r:12,t:18,b:36}},{displayModeBar:false,responsive:true});Plotly.newPlot("airline-cause-chart",[{type:"bar",name:"Weather",x:airlines.map(a=>a[1]),y:airlines.map(a=>a[5]),marker:{color:"#ff8a55"}},{type:"bar",name:"Carrier",x:airlines.map(a=>a[1]),y:airlines.map(a=>a[6]),marker:{color:"#ffc857"}},{type:"bar",name:"Late aircraft",x:airlines.map(a=>a[1]),y:airlines.map(a=>a[7]),marker:{color:"#43c6e7"}}],{...plotLayout,barmode:"group"},{displayModeBar:false,responsive:true})}
function renderRouteRankings(){if(!window.Plotly)return;const sorted=[...routeSummary].sort((a,b)=>b.delay-a.delay);document.querySelector("#route-table").innerHTML=sorted.map(r=>`<tr class="route-row" data-route="${r.route}"><td><b>${r.route}</b></td><td>${fmt(r.flights)}</td><td>${r.delay.toFixed(1)}m</td><td>${r.cancel.toFixed(1)}%</td><td>${r.variability.toFixed(1)}m</td><td><span class="severity ${r.severity}">${r.severity.toUpperCase()}</span></td></tr>`).join("");document.querySelectorAll(".route-row").forEach(row=>{row.onmouseenter=()=>highlightRoute(routeSummary.find(r=>r.route===row.dataset.route));row.onclick=row.onmouseenter});Plotly.newPlot("route-ranking-chart",[{type:"bar",orientation:"h",y:sorted.map(r=>r.route),x:sorted.map(r=>r.delay),marker:{color:sorted.map(r=>severityColor(r.severity))},hovertemplate:"%{y}: %{x:.1f} min<extra></extra>"}],{...plotLayout,margin:{l:72,r:15,t:18,b:34},yaxis:{autorange:"reversed"}},{displayModeBar:false,responsive:true});highlightRoute(selectedRoute||sorted[0])}
function renderSeasonal(){if(!window.Plotly)return;document.querySelector("#season-cards").innerHTML=seasons.map(s=>`<article class="season-card"><small>${s[0].toUpperCase()} OPERATIONS</small><strong>${s[1].toFixed(1)}m</strong><p>${s[2].toFixed(1)}% cancelled · ${s[3]}% weather share</p></article>`).join("");Plotly.newPlot("season-line-chart",[{x:seasons.map(s=>s[0]),y:seasons.map(s=>s[1]),name:"Average delay",mode:"lines+markers",line:{color:"#43c6e7",width:3}},{x:seasons.map(s=>s[0]),y:seasons.map(s=>s[2]*7),name:"Cancellation index",mode:"lines+markers",line:{color:"#ff8a55",width:2,dash:"dot"}}],plotLayout,{displayModeBar:false,responsive:true});Plotly.newPlot("season-bar-chart",[{type:"bar",name:"Weather",x:seasons.map(s=>s[0]),y:seasons.map(s=>s[3]),marker:{color:"#ff8a55"}},{type:"bar",name:"NAS",x:seasons.map(s=>s[0]),y:seasons.map(s=>s[4]),marker:{color:"#43c6e7"}}],{...plotLayout,barmode:"group"},{displayModeBar:false,responsive:true})}
function refreshDashboard(){document.querySelector("#threshold-value").textContent=`${document.querySelector("#delay-threshold").value} MIN`;renderMap();renderTrend();renderCauses();renderCauseAnalysis();updateGlobalStats()}
function setupSearch(){const input=document.querySelector("#airport-search"),results=document.querySelector("#search-results");input.addEventListener("input",()=>{const q=input.value.trim().toLowerCase(),list=q?airports.filter(a=>`${a.code} ${a.name} ${a.city}`.toLowerCase().includes(q)).slice(0,6):[];results.innerHTML=list.map(a=>`<button data-code="${a.code}"><b>${a.code}</b> · ${a.city}, ${a.state}</button>`).join("");results.classList.toggle("show",!!list.length);results.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectAirport(byCode(b.dataset.code),true);input.value="";results.classList.remove("show")})});document.addEventListener("click",e=>{if(!e.target.closest(".search"))results.classList.remove("show")})}
function init(){airports.forEach(a=>document.querySelector("#network-airport").add(new Option(`${a.code} · ${a.city}`,a.code)));document.querySelectorAll("#map-layer,#map-metric,#airport-type,#route-lines").forEach(el=>el.addEventListener("change",renderMap));document.querySelectorAll("#year-filter,#season-filter,#airline-filter").forEach(el=>el.addEventListener("change",refreshDashboard));document.querySelector("#delay-threshold").addEventListener("input",refreshDashboard);document.querySelector("#cause-group").addEventListener("change",renderCauseAnalysis);document.querySelector("#network-airport").onchange=e=>selectAirport(byCode(e.target.value));document.querySelector("#route-limit").onchange=renderNetwork;setupSearch();renderMap();renderRanking();renderComparison();renderHubAnalysis();renderCauseAnalysis();renderAirlines();renderRouteRankings();renderSeasonal();selectAirport(selected)}
init();window.addEventListener("resize",()=>{renderComparison();renderNetwork()});
